services:
  nodejs:
    container_name: swiftorder
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodejs.rule=Host(`swiftorder.didierdjakoua.site`)"
      - "traefik.http.routers.nodejs.entrypoints=websecure"
      - "traefik.http.routers.nodejs.tls=true"
      - "traefik.http.services.nodejs.loadbalancer.server.port=3030"
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://root:my-secret-pw@156.67.27.35:4321/swiftorder?sslmode=disable"
      REDIS_URL: "redis://:my-secret-pw@redis:6379/1"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true

# services:
#   nodejs:
#     build: .
#     ports:
#       - 3030:3030
#     restart: unless-stopped
#     environment:
#       DATABASE_URL: "postgres://root:my-secret-pw@156.67.27.35:4321/swiftorder?sslmode=disable"
#       PORT: "3030"
